pragma Singleton

import QtQuick
import Quickshell
import Quickshell.Io
import qs.Common
import qs.Services

Singleton {
    id: svc

    property string ansyncctlPath: "ansyncctl"
    property int pollIntervalMs: 2000
    property bool notificationBridge: false

    property var devices: []
    property bool daemonAvailable: false
    property string lastError: ""

    // Per-device per-stream local activity cache. The daemon doesn't
    // (yet) emit per-stream signals so we optimistically flip these
    // bits on user action and reset on device-offline. Stale state is
    // recoverable: user clicks the toggle again and the daemon's
    // ShowScreen / HideScreen are both idempotent.
    //   { deviceId: { mirror, mic, camera, audio } }
    property var streams: ({})

    signal pairFinished(bool ok, string message)
    signal adbDevicesListed(var serials)

    // Wi-Fi PIN pair surface (the new D-Bus flow). All callers
    // subscribe to these — `AnsyncWidget` reuses them for the popout
    // candidate picker + PIN modal.
    signal wifiCandidatesFound(var candidates)
    signal wifiPairStarted(string sessionPath)
    signal wifiPairAwaitingPin(string sessionPath, string hostName, string address)
    signal wifiPairCompleted(string deviceId, string name)
    signal wifiPairFailed(string reason)
    // NB: `devicesChanged` is auto-generated by QML for the `devices`
    // property below — assigning to `svc.devices` emits it. Declaring
    // it manually here would duplicate the signal and refuse to load.

    // Connectivity tri-state mapping (mirrors `ansync_dbus::ConnState`):
    //   active        → live + receiving streams (semaphore green)
    //   authenticated → Noise XX done, no Hello yet (yellow)
    //   pairing       → cable / Wi-Fi bootstrap mid-flight (yellow)
    //   disconnected  → known peer, no live link (gray)
    function stateLabel(state) {
        switch (state) {
            case "active": return "Live"
            case "authenticated": return "Linking…"
            case "pairing": return "Pairing"
            case "disconnected": return "Offline"
            default: return state || "Unknown"
        }
    }
    function isLive(state)    { return state === "active" }
    function isPending(state) { return state === "authenticated" || state === "pairing" }

    readonly property string busName: "org.gameros.Ansync1"
    readonly property string managerPath: "/org/gameros/Ansync1/Manager"
    readonly property string managerIface: "org.gameros.Ansync1.Manager"
    readonly property string deviceIface: "org.gameros.Ansync1.Device"
    readonly property string permIface: "org.gameros.Ansync1.Permissions"

    function devicePath(id) { return "/org/gameros/Ansync1/Device/" + id }
    function permPath(id) { return "/org/gameros/Ansync1/Permissions/" + id }
    readonly property string pairSessionIface: "org.gameros.Ansync1.PairingSession"

    // ────────────────────────── stream state ──────────────────────────

    function _ensureStreams(id) {
        if (!svc.streams[id]) {
            const next = Object.assign({}, svc.streams)
            next[id] = { mirror: false, mic: false, camera: false, audio: false }
            svc.streams = next
        }
    }

    function isStreamOn(id, kind) {
        const e = svc.streams[id]
        return e ? (e[kind] === true) : false
    }

    function _setStream(id, kind, on) {
        svc._ensureStreams(id)
        const next = Object.assign({}, svc.streams)
        next[id] = Object.assign({}, next[id], {})
        next[id][kind] = on
        svc.streams = next
    }

    function _clearAllStreams(id) {
        if (!svc.streams[id]) return
        const next = Object.assign({}, svc.streams)
        next[id] = { mirror: false, mic: false, camera: false, audio: false }
        svc.streams = next
    }

    function poll() {
        Proc.runCommand("ansync.list",
            ["busctl", "--user", "--json=short", "call", busName,
             managerPath, managerIface, "ListDevices"],
            (out, code) => {
                if (code !== 0) {
                    if (svc.daemonAvailable) {
                        svc.daemonAvailable = false
                        svc.devices = []
                    }
                    return
                }
                svc.daemonAvailable = true
                try {
                    const parsed = JSON.parse(out)
                    const ids = parsed.data[0] || []
                    svc._fetchAllProps(ids)
                } catch (e) {
                    svc.lastError = "ListDevices parse: " + e
                }
            }, 0)
    }

    function _fetchAllProps(ids) {
        // Reassigning `devices` (even to an empty array) fires the
        // auto-generated `devicesChanged` signal; no manual emit needed.
        if (ids.length === 0) { svc.devices = []; return }
        const next = []
        let pending = ids.length
        for (const id of ids) {
            const captureId = id
            Proc.runCommand("ansync.props." + captureId,
                ["busctl", "--user", "--json=short", "call", busName,
                 devicePath(captureId), "org.freedesktop.DBus.Properties",
                 "GetAll", "s", deviceIface],
                (out, code) => {
                    if (code === 0) {
                        try {
                            const parsed = JSON.parse(out)
                            const dict = parsed.data[0] || {}
                            const get = key => dict[key] ? dict[key].data : null
                            const state = get("State") || "disconnected"
                            next.push({
                                id: captureId,
                                name: get("Name") || captureId.substring(0, 8),
                                state: state,
                                caps: get("Capabilities") || [],
                                battery: get("BatteryLevel") || 0,
                                address: get("Address") || "",
                                live: svc.isLive(state),
                                pending: svc.isPending(state)
                            })
                        } catch (e) {
                            svc.lastError = "GetAll parse " + captureId + ": " + e
                            next.push({id: captureId, name: captureId.substring(0,8),
                                       state: "disconnected", caps: [], battery: 0,
                                       address: "", live: false, pending: false})
                        }
                    }
                    if (--pending === 0) {
                        svc.devices = next.sort((a, b) => a.name.localeCompare(b.name))
                    }
                }, 0)
        }
    }

    /** Apply a single (id, state) update in-place without re-polling
     *  every device's properties. Driven by the
     *  `Manager.DeviceConnectivityChanged` signal so the semaphore
     *  flips in real time without waiting for the next poll tick. */
    function _patchState(id, state) {
        const next = svc.devices.slice()
        let touched = false
        for (let i = 0; i < next.length; ++i) {
            if (next[i].id === id) {
                next[i] = Object.assign({}, next[i], {
                    state: state,
                    live: svc.isLive(state),
                    pending: svc.isPending(state)
                })
                touched = true
                break
            }
        }
        if (touched) {
            svc.devices = next
        } else {
            // First time we see this id — fall through to a property
            // fetch so we get a full row.
            svc._fetchAllProps([id])
        }
        // Device went offline → drop any stale stream bits the toggle
        // logic was hanging on to (otherwise the icon stays "on" after
        // the peer dropped its capture).
        if (state === "disconnected") {
            svc._clearAllStreams(id)
        }
    }

    function _busctl(cmd, label) {
        Proc.runCommand("ansync.call." + label + "." + Date.now(), cmd,
            (out, code) => {
                if (code === 0) {
                    if (typeof ToastService !== "undefined") {
                        ToastService.showInfo("Ansync", label + " ok")
                    }
                    svc.poll()
                } else {
                    if (typeof ToastService !== "undefined") {
                        ToastService.showError("Ansync", label + " failed (" + code + ")")
                    }
                    svc.lastError = label + " exit=" + code
                }
            }, 0)
    }

    function showScreen(id) {
        _busctl(["busctl","--user","call",busName,devicePath(id),deviceIface,"ShowScreen"],
                "ShowScreen")
    }
    function hideScreen(id) {
        _busctl(["busctl","--user","call",busName,devicePath(id),deviceIface,"HideScreen"],
                "HideScreen")
    }
    function syncClipboard(id) {
        _busctl(["busctl","--user","call",busName,devicePath(id),deviceIface,"SyncClipboard"],
                "SyncClipboard")
    }
    function startMic(id) {
        _busctl(["busctl","--user","call",busName,devicePath(id),deviceIface,"StartMicrophone"],
                "StartMicrophone")
    }
    function stopMic(id) {
        _busctl(["busctl","--user","call",busName,devicePath(id),deviceIface,"StopMicrophone"],
                "StopMicrophone")
    }
    function startAudio(id, direction) {
        _busctl(["busctl","--user","call",busName,devicePath(id),deviceIface,
                 "StartAudioRoute","s",direction], "StartAudioRoute")
    }
    function stopAudio(id) {
        _busctl(["busctl","--user","call",busName,devicePath(id),deviceIface,"StopAudioRoute"],
                "StopAudioRoute")
    }
    function startCamera(id, cfg) {
        _busctl(["busctl","--user","call",busName,devicePath(id),deviceIface,
                 "StartCamera","suuyussb",
                 String(cfg.cameraId), String(cfg.width), String(cfg.height),
                 String(cfg.fps), String(cfg.bitrateKbps),
                 cfg.codec, cfg.aspect, cfg.stabilization ? "true" : "false"],
                "StartCamera")
    }
    function stopCamera(id) {
        _busctl(["busctl","--user","call",busName,devicePath(id),deviceIface,"StopCamera"],
                "StopCamera")
    }
    function forget(id) {
        _busctl(["busctl","--user","call",busName,managerPath,managerIface,
                 "ForgetDevice","s",id], "ForgetDevice")
    }
    function refreshPeers() {
        _busctl(["busctl","--user","call",busName,managerPath,managerIface,"RefreshPeers"],
                "RefreshPeers")
    }

    // ────────────────────────── stream toggles ──────────────────────────

    function toggleScreen(id) {
        if (svc.isStreamOn(id, "mirror")) {
            svc.hideScreen(id); svc._setStream(id, "mirror", false)
        } else {
            svc.showScreen(id); svc._setStream(id, "mirror", true)
        }
    }

    function toggleMic(id) {
        if (svc.isStreamOn(id, "mic")) {
            svc.stopMic(id); svc._setStream(id, "mic", false)
        } else {
            svc.startMic(id); svc._setStream(id, "mic", true)
        }
    }

    function toggleCamera(id, cfg) {
        if (svc.isStreamOn(id, "camera")) {
            svc.stopCamera(id); svc._setStream(id, "camera", false)
        } else {
            svc.startCamera(id, cfg); svc._setStream(id, "camera", true)
        }
    }

    function toggleAudio(id, direction) {
        if (svc.isStreamOn(id, "audio")) {
            svc.stopAudio(id); svc._setStream(id, "audio", false)
        } else {
            svc.startAudio(id, direction); svc._setStream(id, "audio", true)
        }
    }

    // ────────────────────────── Wi-Fi PIN pair ──────────────────────────

    /// Browse the LAN for pair-ready companions. Emits `wifiCandidatesFound`
    /// with `[{name, addr, pubkey}]`. Empty list on any failure — the UI
    /// should surface that as "nothing found".
    function browseAvailable(seconds) {
        const secs = String(seconds || 5)
        Proc.runCommand("ansync.browse." + Date.now(),
            ["busctl","--user","--json=short","call",busName,
             managerPath, managerIface, "BrowseAvailable", "u", secs],
            (out, code) => {
                if (code !== 0) {
                    svc.wifiCandidatesFound([])
                    return
                }
                try {
                    const parsed = JSON.parse(out)
                    const arr = parsed.data[0] || []
                    const out2 = arr.map(t => ({
                        name: t[0], addr: t[1], pubkey: t[2]
                    }))
                    svc.wifiCandidatesFound(out2)
                } catch (e) {
                    svc.lastError = "BrowseAvailable parse: " + e
                    svc.wifiCandidatesFound([])
                }
            }, 0)
    }

    /// Kick off a Wi-Fi pair against `addr` (IPv4:port or [IPv6]:port).
    /// `pubkey` is the hex string the daemon's BrowseAvailable returned
    /// — pass empty to skip verification (`--remote-addr` style).
    /// Emits `wifiPairStarted(sessionPath)` and triggers
    /// `wifiPairAwaitingPin` once the daemon's worker hits the PIN
    /// challenge.
    function startWifiPair(addr, pubkey) {
        Proc.runCommand("ansync.startpair." + Date.now(),
            ["busctl","--user","--json=short","call",busName,
             managerPath, managerIface, "StartPairing", "ss", addr, pubkey || ""],
            (out, code) => {
                if (code !== 0) {
                    svc.wifiPairFailed("StartPairing exit=" + code)
                    return
                }
                try {
                    const parsed = JSON.parse(out)
                    const path = parsed.data[0]
                    svc.wifiPairStarted(path)
                    // Immediately fetch session props in case we missed
                    // the awaiting_pin transition between StartPairing
                    // returning and our monitor subscribing.
                    svc._pollPairSession(path)
                } catch (e) {
                    svc.wifiPairFailed("StartPairing parse: " + e)
                }
            }, 0)
    }

    function submitPin(sessionPath, pin) {
        _busctl(["busctl","--user","call",busName,sessionPath,
                 pairSessionIface,"SubmitPin","s",pin], "SubmitPin")
    }

    function cancelPair(sessionPath) {
        _busctl(["busctl","--user","call",busName,sessionPath,
                 pairSessionIface,"Cancel"], "Cancel pair")
    }

    /// Pull all PairingSession properties off the bus and, if the
    /// session is sitting on awaiting_pin, emit `wifiPairAwaitingPin`
    /// with the resolved host name + address. Called both from
    /// `startWifiPair` (to catch the race) and `_onMonitorLine` (when
    /// a State PropertiesChanged lands).
    function _pollPairSession(path) {
        Proc.runCommand("ansync.pairprops." + Date.now(),
            ["busctl","--user","--json=short","call",busName,
             path, "org.freedesktop.DBus.Properties", "GetAll", "s", pairSessionIface],
            (out, code) => {
                if (code !== 0) return
                try {
                    const parsed = JSON.parse(out)
                    const dict = parsed.data[0] || {}
                    const get = key => dict[key] ? dict[key].data : ""
                    const state = get("State")
                    if (state === "awaiting_pin") {
                        svc.wifiPairAwaitingPin(path,
                            get("HostName") || "device",
                            get("Address") || "")
                    } else if (state === "failed") {
                        svc.wifiPairFailed(get("Error") || "pair failed")
                    }
                } catch (e) {
                    svc.lastError = "pair props parse: " + e
                }
            }, 0)
    }

    function setPerm(id, flag, value) {
        _busctl(["busctl","--user","call",busName,permPath(id),permIface,
                 "Set","sb",flag, value ? "true" : "false"], "Set " + flag)
    }
    function resetPerms(id) {
        _busctl(["busctl","--user","call",busName,permPath(id),permIface,"Reset"],
                "Reset perms")
    }
    function getPerm(id, flag, cb) {
        Proc.runCommand("ansync.perm." + id + "." + flag,
            ["busctl","--user","--json=short","call",busName,
             permPath(id), permIface, "Get", "s", flag],
            (out, code) => {
                if (code !== 0) { cb(false); return }
                try { cb(JSON.parse(out).data[0] === true) }
                catch (e) { cb(false) }
            }, 0)
    }

    function listAdbDevices() {
        Proc.runCommand("ansync.adb.list", ["adb", "devices"],
            (out, code) => {
                if (code !== 0) {
                    svc.adbDevicesListed([])
                    return
                }
                const serials = []
                const lines = out.split("\n")
                for (let i = 1; i < lines.length; ++i) {
                    const parts = lines[i].trim().split(/\s+/)
                    if (parts.length >= 2 && parts[1] === "device") {
                        serials.push(parts[0])
                    }
                }
                svc.adbDevicesListed(serials)
            }, 0)
    }

    function pair(serial, displayName) {
        const cmd = [ansyncctlPath, "pair"]
        if (serial && serial.length > 0) { cmd.push("--serial"); cmd.push(serial) }
        if (displayName && displayName.length > 0) {
            cmd.push("--name"); cmd.push(displayName)
        }
        Proc.runCommand("ansync.pair." + Date.now(),
            ["sh", "-c", cmd.map(a => "'" + a.replace(/'/g, "'\\''") + "'").join(" ") + " 2>&1"],
            (out, code) => {
                svc.pairFinished(code === 0, out)
                if (code === 0) svc.refreshPeers()
            }, 0)
    }

    property Timer _pollTimer: Timer {
        // Now that state is signal-driven via `_busMonitor`, the
        // timer is just a safety net for daemon restarts (signal
        // subscriptions drop when the daemon dies and re-arm on
        // reconnect). Slower interval keeps it cheap.
        interval: Math.max(svc.pollIntervalMs * 4, 8000)
        running: true
        repeat: true
        triggeredOnStart: true
        onTriggered: svc.poll()
    }

    /**
     * Single gdbus monitor subscription for the entire ansync surface.
     * Routes `Manager.DeviceConnectivityChanged` into in-place state
     * patches (cheap, real-time) and — when enabled —
     * `Device.NotificationPosted` into the freedesktop notification
     * bus so phone notifications surface on the desktop.
     */
    property Process _busMonitor: Process {
        command: ["gdbus", "monitor", "--session",
                  "--dest", "org.gameros.Ansync1"]
        running: true
        stdout: SplitParser {
            onRead: line => svc._onMonitorLine(line)
        }
    }

    readonly property var _connRe:
        /Manager\.DeviceConnectivityChanged\s*\('([^']+)',\s*'([^']+)'\)/
    readonly property var _streamRe:
        /(\/org\/gameros\/Ansync1\/Device\/[^:]+):\s+org\.gameros\.Ansync1\.Device\.StreamStateChanged\s*\('([^']+)',\s*(true|false)\)/
    readonly property var _notifRe:
        /Device\.NotificationPosted\s*\(uint64\s+(\d+),\s*'([^']*)',\s*'([^']*)',\s*'([^']*)'\)/
    readonly property var _pairPropRe:
        /(\/org\/gameros\/Ansync1\/Pair\/[^:]+):\s+org\.freedesktop\.DBus\.Properties\.PropertiesChanged/
    readonly property var _pairCompletedRe:
        /(\/org\/gameros\/Ansync1\/Pair\/[^:]+):\s+org\.gameros\.Ansync1\.PairingSession\.Completed\s*\('([^']+)',\s*'([^']*)'\)/
    readonly property var _pairFailedRe:
        /(\/org\/gameros\/Ansync1\/Pair\/[^:]+):\s+org\.gameros\.Ansync1\.PairingSession\.Failed\s*\('([^']*)'\)/

    function _onMonitorLine(line) {
        const c = line.match(svc._connRe)
        if (c) {
            svc._patchState(c[1], c[2])
            return
        }
        const sr = line.match(svc._streamRe)
        if (sr) {
            const id = sr[1].split("/").pop()
            // Daemon emits `screen` for the mirror tile; the local
            // stream cache keys the toggle off `mirror` (the user-facing
            // label). Translate so signal-driven updates land on the
            // same key the UI is reading.
            const kind = sr[2] === "screen" ? "mirror" : sr[2]
            svc._setStream(id, kind, sr[3] === "true")
            return
        }
        const pc = line.match(svc._pairCompletedRe)
        if (pc) {
            svc.wifiPairCompleted(pc[2], pc[3])
            svc.refreshPeers()
            return
        }
        const pf = line.match(svc._pairFailedRe)
        if (pf) {
            svc.wifiPairFailed(pf[2] || "pair failed")
            return
        }
        const pp = line.match(svc._pairPropRe)
        if (pp) {
            // PropertiesChanged doesn't carry the new value in a shape
            // we can easily reuse here (gdbus' textual rendering of
            // variants is annoying to parse). Re-poll the session.
            svc._pollPairSession(pp[1])
            return
        }
        if (svc.notificationBridge) {
            const n = line.match(svc._notifRe)
            if (n) {
                const app = n[2], title = n[3], body = n[4]
                const summary = title.replace(/"/g, "'")
                const description = body.replace(/"/g, "'")
                Quickshell.execDetached([
                    "gdbus", "call", "--session",
                    "--dest", "org.freedesktop.Notifications",
                    "--object-path", "/org/freedesktop/Notifications",
                    "--method", "org.freedesktop.Notifications.Notify",
                    "Ansync · " + app, "0", "smartphone",
                    summary, description, "[]", "{}", "5000"
                ])
            }
        }
    }
}
